### ISSUE TITLE
Use string interpolation here

### ISSUE THREAD

**Issue by Bencargs** [LouisWhite15/R6Tab.NET#1]
https://github.com/LouisWhite15/R6Tab.NET/blob/22ecc48a7553c8e66ccb33c0b0fe70f3a93ebd84/R6TabApi.cs#L21

**Comment by LouisWhite15** [comment]
Good catch

**Comment by Denifia** [comment]
For an even better approach, use a Uri builder.

**Comment by LouisWhite15** [comment]
Done boiz
